# Generated by Django 3.2.9 on 2021-11-18 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20211118_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='starred',
            field=models.IntegerField(blank=True, max_length=1, null=True),
        ),
    ]
