# Generated by Django 3.2.9 on 2021-11-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_auto_20211118_1431'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='starred',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
