# Generated by Django 3.2.9 on 2021-11-18 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_starred'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categories'},
        ),
    ]
