# Generated by Django 3.2.9 on 2021-11-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='location',
            field=models.CharField(blank=True, max_length=56),
        ),
    ]
